name: Leetcode practice
on:
  push:
    branches: [ master ]
  workflow_dispatch:
jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Install cmake
      run: |
        sudo apt install -y cmake

    - name: Build repository
      run: |
        cd ${{github.workspace}}
        cmake -B build -S .
        cmake --build build

    - name: Test
      run: |
        cd ${{github.workspace}}/build
        ctest 