name: Leetcode practice
env:
  POCL: pocl
  OCL_ICD: ocl-icd
  ISA_SIMULATOR: ventus-gpgpu-isa-simulator
  BUILD_TYPE: Release
  VENTUS_DRIVER: ventus-driver
  RODINIA: gpu-rodinia
on:
  push:
    branches: [ master ]
    - cron: '0 2 * * *' # Runs at 2am everyday
  workflow_dispatch:
jobs:
  build:
    runs-on: [ubuntu-latest, windows-latest, macos-latest]
    steps:

    - name: Install Ninja
      uses: llvm/actions/install-ninja@main

    - name: Build repository
      run: |
        cmake -B build -S .
        cmake --build build

    - name: Test
      run: |
        cd ${{github.workspace}}/build
        ctest 