name: Leetcode practice
on:
  push:
    branches: [ master ]
  workflow_dispatch:
jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:

    - name: Install Ninja
      uses: llvm/actions/install-ninja@main

    - name: Build repository
      run: |
        cd ${{github.workspace}}
        cmake -B build -S .
        cmake --build build

    - name: Test
      run: |
        cd ${{github.workspace}}/build
        ctest 